CREATE TABLE users (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    fName VARCHAR(50) NOT NULL,
    lName VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    trophies INT(11) NOT NULL DEFAULT 1200,
    wins INT(11) NOT NULL DEFAULT 0,
    losses INT(11) NOT NULL DEFAULT 0,
    profilepic VARCHAR(255) NOT NULL DEFAULT '../images/users/base_user.png',
    bio TINYTEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastplayed TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
